---
title: "Лабораторна робота № 3. Розвідувальний аналіз даних"
author: "Хань Євгеній"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: united
---

**Мета:** Виконати розвідувальний аналіз даних та побудувати модель зниження розмірності на основі методу головних компонент (PCA) для датасету `heptathlon`

## Виконання роботи {.tabset}


### Хід роботи

```{r lab2_full_code_block, echo=TRUE, message=FALSE, warning=FALSE}
library(FactoMineR)
library(factoextra)
library(tidyverse)
library(knitr)
library(kableExtra)
library(PerformanceAnalytics)

athletes <- c("Joyner-Kersee (USA)", "John (GDR)", "Behmer (GDR)", "Sablovskaite (URS)", 
              "Choubenkova (URS)", "Schulz (GDR)", "Fleming (AUS)", "Greiner (USA)", 
              "Scheider (SWI)", "Hautenauve (BEL)", "Hagger (GB)", "Burge (AUS)", 
              "Brown (USA)", "Inanli (TUR)", "Skarabord (NOR)", "Hentze (RFA)", 
              "Blasser (AUT)", "Hui-Ing (TAI)", "Schelbert (SWI)", "Wijnsma (HOL)", 
              "Ruotsalainen (FIN)", "Bremigan (USA)", "Gunell (FIN)", "Mulliner (GB)", 
              "Launa (PNG)")

heptathlon_data <- data.frame(
  hurdles = c(12.69, 12.85, 13.20, 13.61, 13.51, 13.75, 13.89, 13.97, 13.84, 14.04, 
              13.83, 14.15, 14.13, 14.93, 14.83, 14.13, 14.30, 14.76, 14.43, 14.59, 
              14.89, 14.44, 14.33, 14.61, 15.68),
  highjump = c(1.86, 1.80, 1.83, 1.80, 1.74, 1.83, 1.77, 1.80, 1.86, 1.80, 1.71, 1.77, 
               1.83, 1.68, 1.74, 1.80, 1.77, 1.74, 1.68, 1.65, 1.65, 1.68, 1.74, 
               1.65, 1.50),
  shot = c(15.80, 16.23, 15.20, 15.23, 15.20, 14.58, 12.88, 14.18, 12.50, 12.72, 13.10, 
           12.98, 13.48, 11.23, 12.23, 13.10, 12.83, 11.60, 12.35, 12.78, 11.80, 
           12.80, 11.55, 12.23, 11.18),
  run200m = c(22.56, 23.65, 23.10, 23.62, 23.32, 24.13, 24.49, 23.97, 24.63, 25.19, 
              24.83, 24.72, 24.81, 26.58, 25.15, 25.05, 24.40, 25.23, 25.46, 25.13, 
              26.04, 25.19, 25.25, 25.32, 27.66),
  longjump = c(7.27, 6.71, 6.68, 6.40, 6.61, 6.13, 6.12, 6.16, 6.00, 6.07, 6.17, 6.05, 
               6.20, 5.23, 5.75, 5.92, 5.80, 5.65, 5.62, 5.87, 5.55, 5.80, 5.85, 
               5.68, 4.88),
  javelin = c(45.66, 50.12, 44.54, 46.84, 46.06, 44.30, 38.20, 42.84, 38.10, 41.24, 
              40.86, 38.32, 42.42, 34.20, 40.06, 41.98, 39.44, 39.70, 39.12, 39.46, 
              38.00, 36.36, 41.14, 39.48, 30.22),
  run800m = c(128.51, 132.54, 124.20, 132.24, 132.20, 131.66, 132.22, 132.79, 134.40, 
              136.26, 137.74, 136.30, 133.07, 150.15, 136.70, 134.10, 132.56, 142.06, 
              138.30, 137.96, 139.69, 137.19, 135.59, 138.97, 163.39),
  score = c(7291, 6897, 6858, 6599, 6608, 6413, 6253, 6267, 6124, 6042, 5996, 5913, 
            5986, 5136, 5456, 5824, 5745, 5489, 5323, 5530, 5293, 5434, 5529, 
            5446, 4580)
)
rownames(heptathlon_data) <- athletes

knitr::kable(summary(heptathlon_data), caption = "Описові статистики") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

data_for_corr <- heptathlon_data[, 1:7]
PerformanceAnalytics::chart.Correlation(data_for_corr, histogram = TRUE, pch = 19)


pca_results <- PCA(heptathlon_data, 
                   quanti.sup = 8,  
                   graph = FALSE) 

print(pca_results)


fviz_eig(pca_results, addlabels = TRUE, ylim = c(0, 60),
         title = "Графік 1: 'Осип' - Пояснена дисперсія")

fviz_pca_var(pca_results, 
             col.var = "contrib", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, 
             title = "Графік 2: PCA - Графік змінних")

fviz_pca_ind(pca_results, 
             col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE, 
             title = "Графік 3: PCA - Графік індивідів")

fviz_pca_biplot(pca_results, 
                repel = TRUE,
                geom.ind = "point", 
                col.ind = "#696969", 
                col.var = "contrib", 
                gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                title = "Графік 4: PCA - Біоплот")